# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b74c3ec9b38ad7789e57b8c9b3b444628977ed840612122050ab46b2fc4638695bda46d953bae8af8781f2afa0b5d9623483aa01a6ece5fac12b3f5ac3f24d1

test:
  secret_key_base: 22a97a8b1d8762cb248cb723a1090c3b5de649b5dd71562bef32fccecfe2a36674980d6aac80a2b15e475c87202545eb9fdbf1a90312d050b0d9b1c0b4047279

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
